
const data = [
    {
        id: "1",
        img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
        title: "Nike Air Monarch IV",
        star: "4",
        gender: "man",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "250",
        company: "Nike",
        color: "white",
        type: "sneakers",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "2",
        img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
        title: "Nike Air Vapormax Plus",
        star: "4",
        gender: "man",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "250",
        company: "Nike",
        color: "red",
        type: "sneakers",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "3",
        img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
        title: "Nike Waffle One Sneaker",
        star: "4",
        gender: "man",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "250",
        company: "Nike",
        color: "green",
        type: "sneakers",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "4",
        img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
        title: "Nike Running Shoe",
        star: "5",
        gender: "man",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "250",
        company: "Nike",
        color: "black",
        type: "sneakers",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "5",
        img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
        title: "Flat Slip On Pumps",
        star: "5",
        gender: "woman",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "250",
        company: "Vans",
        color: "green",
        type: "flats",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "6",
        img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
        title: "Knit Ballet Flat",
        star: "4",
        gender: "woman",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "140",
        company: "Knit",
        color: "black",
        type: "flats",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },

    {
        id: "7",
        img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
        title: "Loafer Flats",
        star: "4",
        gender: "woman",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "140",
        company: "Vans",
        color: "white",
        type: "flats",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },

    {
        id: "8",
        img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
        title: "Nike Zoom Freak",
        star: "4",
        gender: "man",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "200",
        company: "Nike",
        color: "green",
        type: "sneakers",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },

    {
        id: "9",
        img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
        title: "Nike Men's Sneaker",
        star: "5",
        gender: "man",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "200",
        company: "Nike",
        color: "blue",
        type: "sneakers",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },

    {
        id: "10",
        img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
        title: "PUMA BLACK-OCE",
        star: "4",
        gender: "man",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "150",
        company: "Puma",
        color: "green",
        type: "sneakers",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "11",
        img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
        title: "Pacer Future Sneaker",
        star: "4",
        gender: "man",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "150",
        company: "Puma",
        color: "red",
        type: "sneakers",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "12",
        img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
        title: "Unisex-Adult Super",
        star: "5",
        gender: "woman",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "150",
        company: "Puma",
        color: "black",
        type: "sneakers",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "13",
        img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
        title: "Roma Basic Sneaker",
        star: "4",
        gender: "man",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "150",
        company: "Puma",
        color: "white",
        type: "sneakers",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "14",
        img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
        title: "Pacer Future Doubleknit",
        star: "5",
        gender: "woman",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "150",
        company: "Puma",
        color: "black",
        type: "sneakers",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },

    {
        id: "15",
        img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
        title: "Fusion Evo Golf Shoe",
        star: "4",
        gender: "man",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "100",
        company: "Puma",
        color: "green",
        type: "sneakers",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "16",
        img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
        title: "Rainbow Chex Skate",
        star: "4",
        gender: "man",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "100",
        company: "Vans",
        color: "red",
        type: "flats",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "17",
        img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
        title: "Low-Top Trainers",
        star: "4",
        gender: "man",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "100",
        company: "Vans",
        color: "white",
        type: "sandals",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "18",
        img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
        title: "Vans Unisex Low-Top",
        star: "5",
        gender: "woman",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "100",
        company: "Vans",
        color: "blue",
        type: "sandals",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "19",
        img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
        title: "Classic Bandana Sneakers",
        star: "5",
        gender: "man",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "50",
        company: "Nike",
        color: "black",
        type: "sandals",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "20",
        img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
        title: "Chunky High Heel",
        star: "5",
        gender: "woman",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "50",
        company: "Vans",
        color: "black",
        type: "heels",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "21",
        img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
        title: "Slip On Stiletto High Heel",
        star: "5",
        gender: "woman",
        category: "new",
        discount: false,
        reviews: "123",
        prevPrice: "",
        price: "100",
        company: "Puma",
        color: "black",
        type: "heels",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "22",
        img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
        title: "DREAM PAIRS Court Shoes",
        star: "4",
        gender: "woman",
        category: "old",
        discount: true,
        reviews: "123",
        prevPrice: "140",
        price: "100",
        company: "Nike",
        color: "red",
        type: "heels",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },

    {
        id: "23",
        img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
        title: "Low Mid Block Heels",
        star: "4",
        gender: "woman",
        category: "old",
        discount: true,
        reviews: "123",
        prevPrice: "200",
        price: "140",
        company: "Heels",
        color: "black",
        type: "heels",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "24",
        img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
        title: "Chunky High Heel",
        star: "4",
        gender: "woman",
        category: "old",
        discount: true,
        reviews: "123",
        prevPrice: "140",
        price: "100",
        company: "Chunky",
        color: "black",
        type: "heels",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "25",
        img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
        title: "Amore Fashion Stilettos",
        star: "4",
        gender: "woman",
        category: "old",
        discount: true,
        reviews: "123",
        prevPrice: "200",
        price: "150",
        company: "Amore",
        color: "white",
        type: "heels",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "26",
        img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
        title: "Bridal Sandals Glitter",
        star: "4",
        gender: "woman",
        category: "old",
        discount: true,
        reviews: "123",
        prevPrice: "140",
        price: "50",
        company: "Bridal",
        color: "black",
        type: "heels",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
    {
        id: "27",
        img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
        title: "Wedding Prom Bridal",
        star: "4",
        gender: "woman",
        category: "old",
        discount: true,
        reviews: "123",
        prevPrice: "140",
        price: "50",
        company: "Garcel",
        color: "black",
        type: "flats",

        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aut, quos commodi dolore non fugiat. Nisi itaque, quia doloremque similique optio provident numquam exercitationem sit necessitatibus minima odio quisquam vero?",
        qty: "10",
        sizes: [
            { name: "35.5", inStock: false },
            { name: "36", inStock: true },
            { name: "37", inStock: true },
            { name: "38", inStock: true },
            { name: "39", inStock: true },
            { name: "40", inStock: true },
            { name: "41", inStock: true },
            { name: "42", inStock: true },
        ],
    },
];

export default data;